---
title: "Basic framework to evaluate/compare models on the Teacher Activity Detection dataset"
author: "Luis P. Prieto"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: kate
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Loading and splitting the data

```{r}
processeddatadir <- '../data/processed'
datafile <- paste(processeddatadir,'completeDataset.csv.gz',sep=.Platform$file.sep)
fulldata <- read.csv(gzfile(datafile))

#table(fulldata$session, fulldata$Activity.win, useNA = "always")
#table(fulldata$session, fulldata$Social.win, useNA = "always")

# We only look for predicting 4 states of activity and 3 of social, the rest (incl.NA) we bunch in 'Other'
fulldata$Activity.clean <- ifelse(is.na(as.character(fulldata$Activity.win)) | 
                                      as.character(fulldata$Activity.win)=='OFF' |
                                      as.character(fulldata$Activity.win)=='TDT' |
                                      as.character(fulldata$Activity.win)=='TEC',
                                  'Other',as.character(fulldata$Activity.win))

fulldata$Social.clean <- ifelse(is.na(as.character(fulldata$Social.win)),
                                  'Other',as.character(fulldata$Social.win))

#table(fulldata$session, fulldata$Activity.clean, useNA = "always")
#table(fulldata$session, fulldata$Social.clean, useNA = "always")

names(fulldata)[7562:7563] <- c('Activity','Social')
fulldata <- fulldata[,-c(1,4,5,6)]
fulldata$Activity <- factor(fulldata$Activity)
fulldata$Social <- factor(fulldata$Social)
```

## Basic split

... one session per teacher, with variety of states of Activity and Social

```{r}

# We build the clean datasets to train models
test <- fulldata[fulldata$session=='case2-day3-session1-teacher2' | fulldata$session=='case1-day1-session1-teacher1',]
train <- fulldata[fulldata$session!='case2-day3-session1-teacher2' & fulldata$session!='case1-day1-session1-teacher1',]

z <- gzfile(paste(processeddatadir,"train.csv.gz",sep=.Platform$file.sep),"w")
write.csv(train, z)
close(z)
z <- gzfile(paste(processeddatadir,"test.csv.gz",sep=.Platform$file.sep),"w")
write.csv(test, z)
close(z)

```

# A basic benchmark: Random Forest

Since RF performed quite well in most cases for our LAK paper dataset, let's try it on the whole dataset and see what comes out, as a baseline for modelling

## Teacher activity

```{r}
library(randomForest)
library(AUC)
# Setup the seeds and training
set.seed(123)
fitA <- randomForest(Activity ~ ., data=train[complete.cases(train[1:7557]),-c(1,2,7559)], 
             ntree=4000, importance=TRUE)
summary(fitA)
test$Activity.pred = predict(fitA, test)
confusionMatrix(test$Activity.pred, test$Activity)
varImpPlot(fitA, scale=FALSE)
auc(roc(test$Activity.pred, test$Activity))
```

## Social plane

```{r}
set.seed(1)
fitS <- randomForest(Social ~ ., data=train[complete.cases(train[1:7557]),-c(1,2,7558)], 
             ntree=4000, importance=TRUE)
summary(fitS)
test$Social.pred = predict(fitS, test)
confusionMatrix(test$Social.pred, test$Social)
varImpPlot(fitS, scale=FALSE)
auc(roc(test$Social.pred, test$Social))
```

# (Add your models here...)
